language: objective-c
osx_image: xcode63

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap

before_script: ./sign_fw.sh

after_script:
 codesign --deep -f -s - "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app"

xcode_workspace: BrewMobile.xcworkspace
xcode_scheme: BrewMobile
xcode_sdk: iphonesimulator
