language: objective-c
osx_image: xcode611

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap

# Path to the Xcode workspace.
#If you're using a project, use xcode_project: ...
xcode_workspace: BrewMobile.xcworkspace

# Define the Xcode scheme to use. Make sure the scheme is
 # "Shared" (in Xcode, menu Product > Scheme > Manage Schemes).
xcode_scheme: BrewMobile

# Instruct Travis to run tests in the simulator instead of a real device
xcode_sdk: iphonesimulator
